 version: "3.0"
	watchtower:
		container_name: watchtower
		image: containrrr/watchtower
	    restart: unless-stopped
		command: --schedule " 0 0 0 * * 0" --cleanup
		volumes:
			-  /var/run/docker.sock:/var/run/docker.sock